RTL_DIR = ../../src

# --------------------------------------------------------
MODULE = test_priority_encoder_32
VERILOG_SOURCES = $(RTL_DIR)/priority_encoder_*.v
TOPLEVEL = priority_encoder_32

# --------------------------------------------------------
SIM = questa
WAVES = 1
TOPLEVEL_LANG = verilog
COCOTB_RESOLVE_X = ZEROS

# --------------------------------------------------------
include $(shell cocotb-config --makefiles)/Makefile.sim