RTL_DIR = ../../src

# --------------------------------------------------------
MODULE = test_bin2bcd_8
VERILOG_SOURCES = $(RTL_DIR)/bin2bcd_8.v
TOPLEVEL = bin2bcd_8

# --------------------------------------------------------
SIM = questa
WAVES = 1
TOPLEVEL_LANG = verilog
COCOTB_RESOLVE_X = ZEROS

# --------------------------------------------------------
include $(shell cocotb-config --makefiles)/Makefile.sim