RTL_DIR = ../../src

# --------------------------------------------------------
MODULE = test_seq_detector
VERILOG_SOURCES = $(RTL_DIR)/seq_detector.v
TOPLEVEL = seq_detector

# --------------------------------------------------------
SIM = questa
WAVES = 1
TOPLEVEL_LANG = verilog
COCOTB_RESOLVE_X = ZEROS

# --------------------------------------------------------
include $(shell cocotb-config --makefiles)/Makefile.sim